GET http://localhost:3000/links/getAllClasses
x-authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldGthbiIsInJvbGUiOiJ0ZWFjaGVyIiwiaWQiOiI2OTQ5NjFlMDE4MDI2MGNiNzgxN2M1NTYiLCJpYXQiOjE3NjY1NzEzNTIsImV4cCI6MTc2NjU3ODU1Mn0.BbV0xFYSA83pwFHT7WQZZbSJYmojYZv_v-iAXET4n2g